apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-configmap
data:
  init-script.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
    CREATE USER 'slt_user'@'%';
    CREATE USER 'dml_user'@'%' identified by 'password';
    GRANT SELECT ON *.* TO 'slt_user'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'dml_user'@'%';
    CREATE DATABASE IF NOT EXISTS `database1`;
    CREATE DATABASE IF NOT EXISTS `database2`;
    FLUSH PRIVILEGES;