apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  selector:
    role: redis-cluster
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis-client
      port: 6379
      targetPort: 6379
    - name: redis-bus
      port: 6380
      targetPort: 6380